"""Auto-garant: deals, their invoices and payouts, the deal-chat pool and the deal log

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-27 12:00:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("creator_id", sa.BigInteger(), nullable=False),
        sa.Column("creator_role", sa.String(length=8), nullable=False),
        sa.Column("buyer_id", sa.BigInteger(), nullable=True),
        sa.Column("seller_id", sa.BigInteger(), nullable=True),
        sa.Column("counterparty_username", sa.String(length=64), nullable=True),
        sa.Column("counterparty_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("terms", sa.Text(), nullable=False),
        sa.Column("terms_hash", sa.String(length=64), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("fee_cents", sa.Integer(), nullable=False),
        sa.Column("buyer_pays_cents", sa.Integer(), nullable=False),
        sa.Column("seller_gets_cents", sa.Integer(), nullable=False),
        sa.Column("fee_bps", sa.Integer(), nullable=False),
        sa.Column("fee_payer", sa.String(length=8), nullable=False),
        sa.Column("delivery_days", sa.Integer(), nullable=False),
        sa.Column("pay_hours", sa.Integer(), nullable=False),
        sa.Column("release_hours", sa.Integer(), nullable=False),
        sa.Column("grace_hours", sa.Integer(), nullable=False),
        sa.Column("admin_only_from_cents", sa.Integer(), nullable=True),
        sa.Column("accept_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pay_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deliver_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("release_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cleanup_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("funded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disputed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_cents", sa.Integer(), nullable=True),
        sa.Column("provider_fee_cents", sa.Integer(), nullable=True),
        sa.Column("release_paused", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("cancel_proposed_by", sa.BigInteger(), nullable=True),
        sa.Column("dispute_by", sa.BigInteger(), nullable=True),
        sa.Column("dispute_reason", sa.Text(), nullable=True),
        sa.Column("resolution", sa.String(length=16), nullable=True),
        sa.Column("verdict_by", sa.BigInteger(), nullable=True),
        sa.Column("verdict_note", sa.Text(), nullable=True),
        sa.Column("seller_share_cents", sa.Integer(), nullable=True),
        sa.Column("buyer_share_cents", sa.Integer(), nullable=True),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("chat_status", sa.String(length=12), server_default=sa.text("'none'"), nullable=False),
        sa.Column("card_message_id", sa.Integer(), nullable=True),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("needs_attention", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "coalesce(seller_share_cents, 0) >= 0 AND coalesce(buyer_share_cents, 0) >= 0 AND (status NOT "
            "IN ('settling', 'completed', 'refunded', 'split') OR coalesce(seller_share_cents, 0) + "
            "coalesce(buyer_share_cents, 0) = buyer_pays_cents - fee_cents)",
            name=op.f("ck_deals_shares"),
        ),
        sa.CheckConstraint("creator_role IN ('buyer', 'seller')", name=op.f("ck_deals_role_valid")),
        sa.CheckConstraint(
            "fee_payer IN ('buyer', 'seller', 'split')", name=op.f("ck_deals_fee_payer_valid")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'awaiting_payment', 'funded', 'delivered', 'disputed', 'settling', "
            "'completed', 'refunded', 'split', 'cancelled', 'expired')",
            name=op.f("ck_deals_status_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'cancelled', 'expired') OR (buyer_id IS NOT NULL AND seller_id IS NOT "
            "NULL)",
            name=op.f("ck_deals_parties_bound"),
        ),
        sa.CheckConstraint(
            "amount_cents > 0 AND fee_cents >= 0 AND seller_gets_cents > 0 AND buyer_pays_cents - "
            "seller_gets_cents = fee_cents",
            name=op.f("ck_deals_money"),
        ),
        sa.CheckConstraint(
            "buyer_id IS NULL OR seller_id IS NULL OR buyer_id <> seller_id",
            name=op.f("ck_deals_parties_differ"),
        ),
        sa.CheckConstraint(
            "verdict_by IS NULL OR (verdict_by <> coalesce(buyer_id, 0) AND verdict_by <> "
            "coalesce(seller_id, 0))",
            name=op.f("ck_deals_judge_not_party"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deals")),
        sa.UniqueConstraint("code", name=op.f("uq_deals_code")),
    )
    op.create_index(op.f("ix_deals_buyer_id"), "deals", ["buyer_id"], unique=False)
    op.create_index(op.f("ix_deals_chat_id"), "deals", ["chat_id"], unique=False)
    op.create_index(op.f("ix_deals_creator_id"), "deals", ["creator_id"], unique=False)
    op.create_index(op.f("ix_deals_seller_id"), "deals", ["seller_id"], unique=False)
    op.create_index(op.f("ix_deals_status"), "deals", ["status"], unique=False)
    op.create_table(
        "deal_chats",
        sa.Column("chat_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("title", sa.String(length=256), nullable=True),
        sa.Column("state", sa.String(length=12), nullable=False),
        sa.Column("deal_id", sa.Integer(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cleanup_step", sa.String(length=16), nullable=True),
        sa.Column("first_message_id", sa.Integer(), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_check",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("problem", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("state <> 'free' OR deal_id IS NULL", name=op.f("ck_deal_chats_free_is_empty")),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name=op.f("fk_deal_chats_deal_id_deals"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("chat_id", name=op.f("pk_deal_chats")),
    )
    op.create_index(op.f("ix_deal_chats_state"), "deal_chats", ["state"], unique=False)
    op.create_index(
        "uq_deal_chats_deal_id",
        "deal_chats",
        ["deal_id"],
        unique=True,
        postgresql_where=sa.text("deal_id IS NOT NULL"),
    )
    op.create_table(
        "deal_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deal_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("media_id", sa.Integer(), nullable=True),
        sa.Column("tg_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name=op.f("fk_deal_events_deal_id_deals"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media_files.id"],
            name=op.f("fk_deal_events_media_id_media_files"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deal_events")),
    )
    op.create_index(op.f("ix_deal_events_deal_id"), "deal_events", ["deal_id"], unique=False)
    op.create_index(
        "uq_deal_events_message",
        "deal_events",
        ["chat_id", "message_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'message'"),
    )
    op.create_table(
        "deal_invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deal_id", sa.Integer(), nullable=False),
        sa.Column("provider_invoice_id", sa.BigInteger(), nullable=False),
        sa.Column("payload", sa.String(length=64), nullable=False),
        sa.Column("pay_url", sa.String(length=512), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("disposition", sa.String(length=12), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_amount", sa.String(length=32), nullable=True),
        sa.Column("fee_amount", sa.String(length=32), nullable=True),
        sa.Column("received_cents", sa.Integer(), nullable=True),
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name=op.f("fk_deal_invoices_deal_id_deals"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deal_invoices")),
        sa.UniqueConstraint("provider_invoice_id", name=op.f("uq_deal_invoices_provider_invoice_id")),
    )
    op.create_index(op.f("ix_deal_invoices_deal_id"), "deal_invoices", ["deal_id"], unique=False)
    op.create_index(op.f("ix_deal_invoices_status"), "deal_invoices", ["status"], unique=False)
    op.create_index(
        "uq_deal_invoices_one_active",
        "deal_invoices",
        ["deal_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "uq_deal_invoices_one_funding",
        "deal_invoices",
        ["deal_id"],
        unique=True,
        postgresql_where=sa.text("disposition = 'funded'"),
    )
    op.create_table(
        "deal_payouts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deal_id", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.String(length=8), nullable=False),
        sa.Column("source_invoice_id", sa.Integer(), nullable=True),
        sa.Column("recipient_id", sa.BigInteger(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("spend_id", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("transfer_id", sa.BigInteger(), nullable=True),
        sa.Column("last_error", sa.String(length=256), nullable=True),
        sa.Column("manual_ref", sa.Text(), nullable=True),
        sa.Column("decided_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "purpose <> 'extra' OR source_invoice_id IS NOT NULL",
            name=op.f("ck_deal_payouts_extra_has_source"),
        ),
        sa.CheckConstraint("amount_cents > 0", name=op.f("ck_deal_payouts_positive")),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name=op.f("fk_deal_payouts_deal_id_deals"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_invoice_id"],
            ["deal_invoices.id"],
            name=op.f("fk_deal_payouts_source_invoice_id_deal_invoices"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deal_payouts")),
        sa.UniqueConstraint("spend_id", name=op.f("uq_deal_payouts_spend_id")),
    )
    op.create_index(op.f("ix_deal_payouts_deal_id"), "deal_payouts", ["deal_id"], unique=False)
    op.create_index(op.f("ix_deal_payouts_recipient_id"), "deal_payouts", ["recipient_id"], unique=False)
    op.create_index(
        "ix_deal_payouts_status_next", "deal_payouts", ["status", "next_attempt_at"], unique=False
    )
    op.create_index(
        "uq_deal_payouts_deal_purpose",
        "deal_payouts",
        ["deal_id", "purpose"],
        unique=True,
        postgresql_where=sa.text("purpose IN ('seller', 'buyer')"),
    )
    op.create_index(
        "uq_deal_payouts_source_invoice",
        "deal_payouts",
        ["source_invoice_id"],
        unique=True,
        postgresql_where=sa.text("source_invoice_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_deal_payouts_source_invoice",
        table_name="deal_payouts",
        postgresql_where=sa.text("source_invoice_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_deal_payouts_deal_purpose",
        table_name="deal_payouts",
        postgresql_where=sa.text("purpose IN ('seller', 'buyer')"),
    )
    op.drop_index("ix_deal_payouts_status_next", table_name="deal_payouts")
    op.drop_index(op.f("ix_deal_payouts_recipient_id"), table_name="deal_payouts")
    op.drop_index(op.f("ix_deal_payouts_deal_id"), table_name="deal_payouts")
    op.drop_table("deal_payouts")
    op.drop_index(
        "uq_deal_invoices_one_funding",
        table_name="deal_invoices",
        postgresql_where=sa.text("disposition = 'funded'"),
    )
    op.drop_index(
        "uq_deal_invoices_one_active",
        table_name="deal_invoices",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(op.f("ix_deal_invoices_status"), table_name="deal_invoices")
    op.drop_index(op.f("ix_deal_invoices_deal_id"), table_name="deal_invoices")
    op.drop_table("deal_invoices")
    op.drop_index(
        "uq_deal_events_message", table_name="deal_events", postgresql_where=sa.text("kind = 'message'")
    )
    op.drop_index(op.f("ix_deal_events_deal_id"), table_name="deal_events")
    op.drop_table("deal_events")
    op.drop_index(
        "uq_deal_chats_deal_id", table_name="deal_chats", postgresql_where=sa.text("deal_id IS NOT NULL")
    )
    op.drop_index(op.f("ix_deal_chats_state"), table_name="deal_chats")
    op.drop_table("deal_chats")
    op.drop_index(op.f("ix_deals_status"), table_name="deals")
    op.drop_index(op.f("ix_deals_seller_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_creator_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_chat_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_buyer_id"), table_name="deals")
    op.drop_table("deals")
    # ### end Alembic commands ###
