"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-26 10:17:32.583230
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity", sa.String(length=32), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_actor_id"), "audit_log", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False)
    op.create_table(
        "backups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sent_file_id", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backups")),
    )
    op.create_table(
        "blacklist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("value", sa.String(length=512), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blacklist")),
        sa.UniqueConstraint("kind", "value", name=op.f("uq_blacklist_kind_value")),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=48), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("nav_label", sa.String(length=64), nullable=False),
        sa.Column("header", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("post_order", sa.Integer(), nullable=False),
        sa.Column("nav_order", sa.Integer(), nullable=False),
        sa.Column("top_slots", sa.Integer(), nullable=False),
        sa.Column("top_prices", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("price_overrides", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("max_items", sa.Integer(), nullable=True),
        sa.Column("is_open", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_visible", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("slug", name=op.f("uq_categories_slug")),
    )
    op.create_table(
        "channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=True),
        sa.Column("invite_link", sa.String(length=256), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_health_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channels")),
        sa.UniqueConstraint("chat_id", name=op.f("uq_channels_chat_id")),
    )
    op.create_table(
        "custom_emoji",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("alt", sa.String(length=32), nullable=False),
        sa.Column("set_name", sa.String(length=128), nullable=True),
        sa.Column("in_catalog", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("catalog_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_custom_emoji")),
    )
    op.create_table(
        "fonts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("set_name", sa.String(length=128), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fonts")),
    )
    op.create_table(
        "fsm_states",
        sa.Column("key", sa.String(length=256), nullable=False),
        sa.Column("state", sa.String(length=256), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_fsm_states")),
    )
    op.create_table(
        "import_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_runs")),
    )
    op.create_table(
        "media_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("file_id", sa.String(length=256), nullable=True),
        sa.Column("file_unique_id", sa.String(length=128), nullable=True),
        sa.Column("bot_id", sa.BigInteger(), nullable=True),
        sa.Column("local_path", sa.String(length=512), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("mime", sa.String(length=128), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_files")),
    )
    op.create_index(op.f("ix_media_files_file_unique_id"), "media_files", ["file_unique_id"], unique=False)
    op.create_table(
        "moderation_cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ref_type", sa.String(length=16), nullable=False),
        sa.Column("ref_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_moderation_cards")),
    )
    op.create_index("ix_moderation_cards_ref", "moderation_cards", ["ref_type", "ref_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dedup_key", sa.String(length=160), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("dedup_key", name=op.f("uq_notifications_dedup_key")),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "staff",
        sa.Column("user_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("added_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_staff")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=256), nullable=True),
        sa.Column("lang", sa.String(length=8), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.Column("captcha_passed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("captcha", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_banned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("report_banned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("blocked_bot", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_source"), "users", ["source"], unique=False)
    op.create_table(
        "channel_posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("block_id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column("extra_message_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dirty", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sent_hash", sa.String(length=64), nullable=True),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("pinned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
            name=op.f("fk_channel_posts_channel_id_channels"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channel_posts")),
        sa.UniqueConstraint(
            "channel_id", "kind", "block_id", name=op.f("uq_channel_posts_channel_id_kind_block_id")
        ),
    )
    op.create_index(op.f("ix_channel_posts_channel_id"), "channel_posts", ["channel_id"], unique=False)
    op.create_table(
        "font_glyphs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("font_id", sa.Integer(), nullable=False),
        sa.Column("char", sa.String(length=8), nullable=False),
        sa.Column("emoji_id", sa.String(length=32), nullable=False),
        sa.Column("alt", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["font_id"], ["fonts.id"], name=op.f("fk_font_glyphs_font_id_fonts"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_font_glyphs")),
        sa.UniqueConstraint("font_id", "char", name=op.f("uq_font_glyphs_font_id_char")),
    )
    op.create_index(op.f("ix_font_glyphs_emoji_id"), "font_glyphs", ["emoji_id"], unique=False)
    op.create_table(
        "import_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("classification", sa.String(length=16), nullable=True),
        sa.Column("parse", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["import_runs.id"],
            name=op.f("fk_import_messages_run_id_import_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_messages")),
        sa.UniqueConstraint("run_id", "message_id", name=op.f("uq_import_messages_run_id_message_id")),
    )
    op.create_index(op.f("ix_import_messages_run_id"), "import_messages", ["run_id"], unique=False)
    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("url_kind", sa.String(length=24), nullable=False),
        sa.Column("raw_fragment", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("hidden_reason", sa.String(length=32), nullable=True),
        sa.Column("listing_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.BigInteger(), nullable=True),
        sa.Column("link_state", sa.String(length=16), nullable=False),
        sa.Column("link_dead_streak", sa.Integer(), nullable=False),
        sa.Column("link_first_dead_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("link_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("link_fingerprint", sa.String(length=256), nullable=True),
        sa.Column("link_grace_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_services_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
    )
    op.create_index(op.f("ix_services_category_id"), "services", ["category_id"], unique=False)
    op.create_index(op.f("ix_services_owner_id"), "services", ["owner_id"], unique=False)
    op.create_index(op.f("ix_services_status"), "services", ["status"], unique=False)
    op.create_table(
        "static_posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("post_order", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=True),
        sa.Column("media_kind", sa.String(length=16), nullable=True),
        sa.Column("link_preview", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media_files.id"],
            name=op.f("fk_static_posts_media_id_media_files"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_static_posts")),
    )
    op.create_table(
        "features",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("top_position", sa.Integer(), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_features_service_id_services"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_features")),
        sa.UniqueConstraint("service_id", "kind", name=op.f("uq_features_service_id_kind")),
    )
    op.create_index(op.f("ix_features_expires_at"), "features", ["expires_at"], unique=False)
    op.create_index(op.f("ix_features_service_id"), "features", ["service_id"], unique=False)
    op.create_index(
        "uq_features_active_top_position",
        "features",
        ["category_id", "top_position"],
        unique=True,
        postgresql_where=sa.text("kind = 'top' AND status = 'active'"),
    )
    op.create_table(
        "link_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.String(length=512), nullable=True),
        sa.Column("fingerprint", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_link_checks_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_link_checks")),
    )
    op.create_index(op.f("ix_link_checks_service_id"), "link_checks", ["service_id"], unique=False)
    op.create_table(
        "moderation_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("moderator_id", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_moderation_requests_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_moderation_requests")),
    )
    op.create_index(
        op.f("ix_moderation_requests_service_id"), "moderation_requests", ["service_id"], unique=False
    )
    op.create_index(op.f("ix_moderation_requests_status"), "moderation_requests", ["status"], unique=False)
    op.create_index(op.f("ix_moderation_requests_user_id"), "moderation_requests", ["user_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("months", sa.Integer(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fulfilled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_orders_service_id_services"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_index(op.f("ix_orders_service_id"), "orders", ["service_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "report_cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("decided_by", sa.BigInteger(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("owner_reply_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_reply", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_report_cases_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_cases")),
    )
    op.create_index(op.f("ix_report_cases_service_id"), "report_cases", ["service_id"], unique=False)
    op.create_index(op.f("ix_report_cases_status"), "report_cases", ["status"], unique=False)
    op.create_table(
        "top_waitlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("top_position", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hold_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_top_waitlist_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_top_waitlist")),
        sa.UniqueConstraint(
            "category_id",
            "top_position",
            "service_id",
            name=op.f("uq_top_waitlist_category_id_top_position_service_id"),
        ),
    )
    op.create_index(op.f("ix_top_waitlist_category_id"), "top_waitlist", ["category_id"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("provider_invoice_id", sa.BigInteger(), nullable=False),
        sa.Column("pay_url", sa.String(length=512), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_asset", sa.String(length=16), nullable=True),
        sa.Column("paid_amount", sa.String(length=64), nullable=True),
        sa.Column("paid_usd_rate", sa.String(length=64), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_invoices_order_id_orders"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        sa.UniqueConstraint("provider_invoice_id", name=op.f("uq_invoices_provider_invoice_id")),
    )
    op.create_index(op.f("ix_invoices_order_id"), "invoices", ["order_id"], unique=False)
    op.create_index(op.f("ix_invoices_status"), "invoices", ["status"], unique=False)
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("reporter_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("media_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["report_cases.id"], name=op.f("fk_reports_case_id_report_cases"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(op.f("ix_reports_case_id"), "reports", ["case_id"], unique=False)
    op.create_index(op.f("ix_reports_reporter_id"), "reports", ["reporter_id"], unique=False)
    op.create_table(
        "scam_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("service_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("category_title", sa.String(length=128), nullable=True),
        sa.Column("category_label", sa.String(length=64), nullable=True),
        sa.Column("owner_id", sa.BigInteger(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("media_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["report_cases.id"],
            name=op.f("fk_scam_entries_case_id_report_cases"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_scam_entries_service_id_services"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scam_entries")),
    )
    op.create_index(op.f("ix_scam_entries_status"), "scam_entries", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scam_entries_status"), table_name="scam_entries")
    op.drop_table("scam_entries")
    op.drop_index(op.f("ix_reports_reporter_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_case_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_invoices_status"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_order_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_top_waitlist_category_id"), table_name="top_waitlist")
    op.drop_table("top_waitlist")
    op.drop_index(op.f("ix_report_cases_status"), table_name="report_cases")
    op.drop_index(op.f("ix_report_cases_service_id"), table_name="report_cases")
    op.drop_table("report_cases")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_service_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_moderation_requests_user_id"), table_name="moderation_requests")
    op.drop_index(op.f("ix_moderation_requests_status"), table_name="moderation_requests")
    op.drop_index(op.f("ix_moderation_requests_service_id"), table_name="moderation_requests")
    op.drop_table("moderation_requests")
    op.drop_index(op.f("ix_link_checks_service_id"), table_name="link_checks")
    op.drop_table("link_checks")
    op.drop_index(
        "uq_features_active_top_position",
        table_name="features",
        postgresql_where=sa.text("kind = 'top' AND status = 'active'"),
    )
    op.drop_index(op.f("ix_features_service_id"), table_name="features")
    op.drop_index(op.f("ix_features_expires_at"), table_name="features")
    op.drop_table("features")
    op.drop_table("static_posts")
    op.drop_index(op.f("ix_services_status"), table_name="services")
    op.drop_index(op.f("ix_services_owner_id"), table_name="services")
    op.drop_index(op.f("ix_services_category_id"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_import_messages_run_id"), table_name="import_messages")
    op.drop_table("import_messages")
    op.drop_index(op.f("ix_font_glyphs_emoji_id"), table_name="font_glyphs")
    op.drop_table("font_glyphs")
    op.drop_index(op.f("ix_channel_posts_channel_id"), table_name="channel_posts")
    op.drop_table("channel_posts")
    op.drop_index(op.f("ix_users_source"), table_name="users")
    op.drop_table("users")
    op.drop_table("staff")
    op.drop_table("settings")
    op.drop_table("notifications")
    op.drop_index("ix_moderation_cards_ref", table_name="moderation_cards")
    op.drop_table("moderation_cards")
    op.drop_index(op.f("ix_media_files_file_unique_id"), table_name="media_files")
    op.drop_table("media_files")
    op.drop_table("import_runs")
    op.drop_table("fsm_states")
    op.drop_table("fonts")
    op.drop_table("custom_emoji")
    op.drop_table("channels")
    op.drop_table("categories")
    op.drop_table("blacklist")
    op.drop_table("backups")
    op.drop_index(op.f("ix_audit_log_created_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor_id"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
