"""service extra and static nav

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 10:36:27.230007
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "services",
        sa.Column(
            "extra",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column("static_posts", sa.Column("nav_label", sa.String(length=64), nullable=True))
    op.add_column(
        "static_posts", sa.Column("nav_order", sa.Integer(), server_default=sa.text("0"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("static_posts", "nav_order")
    op.drop_column("static_posts", "nav_label")
    op.drop_column("services", "extra")
    # ### end Alembic commands ###
